services:
  - type: web
    name: spring-boot-app
    env: ubuntu
    buildCommand: |
      apt-get update
      apt-get install -y maven
      mvn clean install
    startCommand: java -jar target/ToDoApp-0.0.1-SNAPSHOT.jar
